version: 0.2
phases:
  install:
    commands:
      - n install 18
      - node --version
  build:
    commands:
      - echo "Lets go team paramicons  x"
      - gradle devparamicons_deployCode --stacktrace
      - echo "just did devparamicons_buildAndDeploy whats next"

